로그인, 프로필화면 [STEP 1] Forest, Volga
2023newkrew/ios-login-profile pull request #1
Opened 2023-01-03 05:30 UTC by forestjae

안녕하세요 라자냐!
Forest와 Volga입니다. Step1 PR 보내드립니다.

## 고민한점

### 텍스트 필드 변경 이벤트
`addTarget` 메서드를 사용하여 텍스트 필드가 변경될 때마다 `textFiledDidChange` 메서드를 사용하게 하여 id길이에 따른 버튼 활성화 로직을 구현했습니다. `UITextFieldDelegate`에 텍스트 필드가 변경 이벤트를 알려주는 메서드가 없어 이러한 방법을 사용했습니다. 다른 방법도 있을지 궁금합니다!

### 다이나믹 타입 및 지역화 적용
다이나믹 타입 및 지역화 적용에 있어서 스토리보드의 기능을 사용하지 않고 코드 베이스로 구현했습니다. 
`UIButton` 같은 경우는 스토리보드에서 해당 속성을 설정할 수 있는 방법이 없어 일관성을 위해 코드베이스로 통일했습니다.
`Localizable` strings파일을 만들어 지역화를 적용했습니다.

## 궁금한점

### 스토리보드를 사용할때의 기준
이번 프로젝트를 진행하면서 UI 컴포넌트들의 기본적인 설정(글꼴, 제약, 색)등은 스토리보드에서 설정해준 반면에, 지역화나 다이나믹 타입 같은 경우는 코드베이스에서 설정을 해주었습니다. 이렇게 같은 컴포넌트에 대한 설정하는 방법이 이원화되면 나중에 유지보수할 때 문제가 될 것 같은데 라자냐는 어떻게 하시는지 궁금합니다!!

2023-01-03 05:34 UTC, Kioding commented
@wonhee009 태그해드립니다 :)

2023-01-03 10:40 UTC, wonhee009 requested changes
수고하셨습니다 :)
코멘트 남겨두었으니 확인 부탁드려요.

"지역화나 다이나믹 타입 같은 경우는 코드베이스에서 설정" 이렇게 결정하게된 배경이 궁금한데요.
말씀해주신 것처럼 이원화되어 있다면 나중에 유지보수 측면에서 좋지 않을거 같습니다.
다른 개발자가 해당 화면을 유지보수 할때에 스토리보드, 코드 둘 다 까봐야할 수 있으니까요.
이게 복잡하지 않은 화면에서는 비용이 적은데 화면이 복잡할수록 비용이 많이 드는 작업일 수 있을거 같습니다.

2023-01-03 10:40 UTC, wonhee009 commented on LoginProfile/ViewController.swift
> +        guard let idText = idTextField.text else { return }
`sender`를 Any로 정의한 이유가 있나요?
`sender: UITextField`로 정의해서 사용할 수 있을거 같습니다.

2023-01-04 00:45 UTC, forestjae commented on LoginProfile/ViewController.swift
> +        guard let idText = idTextField.text else { return }
말씀해 주신대로 구체적으로 타입을 명시하는게 좋아보이네요!
다만, 현재 구현 상황에서는 sender를 파라미터로 받을 필요가 없어, 해당 파라미터를 삭제하는 방향으로 변경했습니다.

2023-01-04 00:47 UTC, forestjae commented
> "지역화나 다이나믹 타입 같은 경우는 코드베이스에서 설정" 이렇게 결정하게된 배경이 궁금한데요.
UIButton의 같은 경우는 스토리보드에서 해당 속성을 설정할 수 있는 방법이 없어 일관성을 위해 코드베이스로 결정했었습니다.

2023-01-04 00:51 UTC, volgaHwang commented
@wonhee009 라자냐 PR 코멘트 주신부분에 대한 답변과 수정사항을 반영했습니다!

2023-01-04 00:56 UTC, wonhee009 commented on LoginProfile/ViewController.swift
> +        guard let idText = idTextField.text else { return }
제가 생각했던 부분은 `sender: UITextField`로 정의하고
``` swift
sender.text
```
이런식으로 text를 받아올 수 있지 않나 싶었는데요.
이 부분은 이후 스텝에서 한 번 더 고민 부탁드립니다.

2023-01-04 00:57 UTC, wonhee009 approved these changes

2023-01-04 00:57 UTC, merged

2023-01-04 01:20 UTC, volgaHwang commented on LoginProfile/ViewController.swift
> +        guard let idText = idTextField.text else { return }
이 부분은 캐치를 못했었네요 감사합니다 !