로그인, 프로필 화면 [STEP 2] Summer, John
2023newkrew/ios-login-profile pull request #2
Opened 2023-01-03 08:26 UTC by limjae

@zdodev 

Summer, John 입니다!! 잘부탁드립니다!! 😃
Localization 부분은 일정상 수요일 이내로 마무리 짓겠습니다!

## 고민한점

1. storyboard와 UIViewController에서의 작성 범위 제한

   모든 UI를 작성함에 있어서 통일성을 주기 위해

   storyboard Inspector내에서 구현이 가능한 부분이 아닌 경우에만

   ViewController에서 코드를 작성하였습니다.

   - ex) TextField에 underline 추가, TextField 변경에 따라 글자 수 검사 후 UIButton 활성화

2. LoginViewController에서 extension을 통해 관심사 분리

```swift
extension LoginViewController {
    func drawUnderline(of textField: UITextField){
        let border = CALayer()
        let underlineWidth = self.view.frame.width - Constant.sideSpace * 2
        border.frame = CGRect(x: 0, y: textField.frame.size.height + Constant.underlineSpace, width: underlineWidth, height: 1)
        border.backgroundColor = UIColor.placeholderText.cgColor
        textField.layer.addSublayer(border)
    }
}
```

코드로 인해 UI가 변경 될 수 있는 로직을 영역을 분리하여 작성했습니다.

## 궁금한점

1. 폴더 구조

   이번 프로젝트에서 기본 설정된 파일들이 많아 카테고리 별로 묶어서 분류를 했습니다.

   하지만 storyboard 파일의 경우 UICompontents 분류에 지정하기에 더 많은 역할을 수행하고 있어 특정 카테고리로 지정하지 못했습니다.

   

   어떤 방법으로 파일을 분류하는 것이 효과적일까요?

   

2. Figma의 디자인 참고 방법

   Figma에 있는 디자인과 최대한 유사한 View를 그리려고 했습니다.

   

   하지만 Apple의 경우 point라는 개념을 사용하여 padding과 같은 constraints를 선언 할 때 1:1 매칭이 안되고

   Dynamic Types 같은 경우 동적으로 크기가 변하기 때문에 Figma의 디자인을 정확히 준수하기 어려웠습니다.

   

   어떠한 방법으로 Figma를 참고하는 것이 좋을까요?

3. Autolayout을 적용 할 때 `Vertical Spacing`과 `Vertical Baseline Standard Spacing` 의 차이점이 궁금합니다.

4. 관심사의 분리 기준

   IBAction으로 TextField의 text가 변화할 때마다 특정 동작을 수행하도록 하였습니다.

   이러한 IBAction은 Extension으로 분리해주는 것이 좋을까요? 그냥 두는 것이 좋을까요? (IBAction이라는 점에서 그냥 두는 것도 좋을 것 같고 TextField와 관련된 것을 따로 빼내어 가독성을 높이기 위해서 분리하는 것도 좋을 것 같습니다.)

   고민이 되는데 조언을 부탁드립니다.

2023-01-03 13:57 UTC, zdodev requested changes
안녕하세요. @limjae , Summer!

Step1 진행 잘해주셨습니다!

먼저 궁금한 점에 대해 얘기해보자면

1. 하나의 스토리보드에 여러 scene 을 생성할 수도 있지만, 카테고리 별로 스토리보드를 생성하고 하나의 scene 만 사용하는 방법도 좋을 것 같습니다. (ex: Login.storyboard, Logout.storyboard...)

2. Figma 의 Inspect 탭, Code 하위 메뉴에서 iOS 를 확인해보시는 것도 하나의 방법이 될 수 있을 것 같습니다! Dynamic Types 의 경우 동적으로 크기가 변하기 때문에 디자이너 분과 의논하시는 것도 좋을 것 같습니다!

3. 해당 부분은 아래의 공식 문서를 참고해보면 좋을 것 같습니다!

[NSLayoutConstraint.Attribute](https://developer.apple.com/documentation/uikit/nslayoutconstraint/attribute)
[Understanding Auto Layout](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/index.html)

4. 관점에 따라 다를 것 같습니다. `extension` 을 관심사의 분리 역할로 사용할 것인지, 기능의 확장으로 사용할 것인지에 따라 다를 것 같습니다. 지금도 좋습니다! `extension` 을 언제 사용할 것인지, 어떤 기준에서 사용할 것인지 고민해보고 사용하신다면 어느쪽이든 좋을 것 같습니다!

그리고 Dynamic type 을 지원하는 폰트가 적용되어 있지만 실제로 Inspector 를 통해 폰트 사이즈를 변경해도 화면 상에서 폰트 사이즈가 변경되지 않습니다. 해당 부분도 확인이 필요할 것 같습니다!

궁금한 점 몇 가지 남겨보았습니다!
의견을 나눠보면 좋겠습니다!🤗

2023-01-03 13:57 UTC, zdodev commented on LoginProfile/Extension/UIColor+Extension.swift
> +    convenience init(red: Int, green: Int, blue: Int, a: Int = 0xFF) {
`a` 파라미터 이름을 축약해서 사용하신 이유가 궁금합니다!

2023-01-03 13:57 UTC, zdodev commented on LoginProfile/UIViewController/LoginViewController.swift
> +class LoginViewController: UIViewController {
이름을 바꿔보셨네요!👍

2023-01-03 13:57 UTC, zdodev commented on LoginProfile/UIViewController/LoginViewController.swift
> +    enum Constant {
상수를 모아서 정의하셨네요! 좋습니다👍

2023-01-03 13:57 UTC, zdodev commented on LoginProfile/UIViewController/LoginViewController.swift
> +    func drawUnderline(of textField: UITextField){
사소한 부분일 수 있지만 `{` 앞에 공백이 빠진 것 같습니다!

2023-01-03 13:57 UTC, zdodev commented on LoginProfile/UIViewController/LoginViewController.swift
> +        let underlineWidth = self.view.frame.width - Constant.sideSpace * 2
`self` 사용하여 접근할 때와 사용하지 않을 때의 기준이 궁금합니다!

2023-01-03 13:57 UTC, zdodev commented on LoginProfile/UIViewController/LoginViewController.swift
> +    @IBAction func idTextFieldChanged(_ sender: Any) {
`sender` 의 타입을 `Any` 정의하신 이유가 궁금합니다!

2023-01-05 01:01 UTC, limjae commented on LoginProfile/Extension/UIColor+Extension.swift
> +    convenience init(red: Int, green: Int, blue: Int, a: Int = 0xFF) {
알파값이랑 가까운 글자로 표현했는데 더 명확하게 alpha로 수정하겠습니다!

2023-01-05 12:00 UTC, zdodev approved these changes
안녕하세요! @limjae , Summer!

피드백 확인하였습니다!

Step1 진행하시느라 고생하셨습니다!👍

2023-01-05 12:00 UTC, merged